import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import AdminLayOut from '@/pagelayout/adminlayout'
import { Box } from '@mui/material'
import ResponsiveDrawer from '@/components/layout/drawer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Time Tracker App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayOut>
        <ResponsiveDrawer  /> 
        <Box sx={{ backgroundColor: "lightgray", width: "100%", height: "100vh", position: "absolute", top: 0 }}>
          {/* Content of the Box */}
        </Box>
      </AdminLayOut>
    </>
  )
}
